import type { NextPage } from 'next'
import Main from './Components/Main'
import Head from 'next/head'
import SideMenu from './Components/SideMenu'
import SideMenu2 from './Components/SideMenu2'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-black h-full  flex'>
        <SideMenu />
        <Main />
        <SideMenu2 />
      </div>
    </div>
  )
}

export default Home
